### ISSUE TITLE
Simple login form (user session) /login

### ISSUE THREAD

**Issue by MathiasCK** [MathiasCK/node-editor-3900#2]
Veldig enkel "login" form.

- Lag en ny side på "/login"
- Her kan bruker skrive inn navnet sitt i et input felt
- Verdien lagres i localstorage eller sessions
- Hvis navnet finnes redirect til editoren -> /
- Hvis navnet ikke finnes redirect alltid til /login

**Comment by hskaftun** [comment]
To-do Session:
-	Controller back-end for log-in handling
-	Make User class for database
-	Logout function 
-	Add different authentication user/admin
-	Restrict RegisterForm to admin
